services:
  tehuset-web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./content:/app/content
      - ./public/assets:/app/public/assets
    restart: unless-stopped
